name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: update apt-get
      run: |
        sudo apt-get update
    - name: install zip, unzip, curl, vim
      run: |
        sudo apt-get install zip unzip curl vim -y
    - name: install sdkman
      run: |
        sudo curl -s "https://get.sdkman.io" | bash
    - name: change bash
      run: |
        sudo -s
    - name: run sdkman
      run: |
        sudo source /root/.sdkman/bin/sdkman-init.sh
    - name: install maven 3.8.7
      run: |
        sudo sdk install maven 3.8.7
    - name: install java 19.0.2-open
      run: |
        sudo sdk install java 19.0.2-open
