name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: update
      run: |
        sudo apt-get update
    - name: install zip, unzip, curl, vim
      run: |
        sudo apt-get install zip unzip curl vim -y
