name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: update apt-get
      run: |
        sudo apt-get update
    - name: install zip, unzip, curl, vim
      run: |
        sudo apt-get install zip unzip curl vim -y
    - name: install sdkman
      run: |
        sudo curl -s "https://get.sdkman.io" | bash
    - name: 檢視當前使用的shell
      run: |
        sudo echo $SHELL
    - name: 檢視當前使用的shell 2
      run: |
        sudo ls -l /bin/sh
    - name: 檢視所有可用的shell
      run: |
        sudo cat /etc/shells
    - name: change shell
      run: |
        sudo dpkg-reconfigure -p critical dash
    - name: run sdkman
      run: |
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
